
name: Manual Send
on:
  workflow_dispatch:
    inputs:
      test_email:
        description: 'Email to send to'
        required: false
        default: 'ralphie.buffalo@colorado.edu'

jobs:
  send_email:

    runs-on: ubuntu-latest
    
    env:
      EMAIL_ADDRESS: ${{ github.event.inputs.test_email }}
      DEV: 'True'
      ALTMETRIC_API_KEY: '${{ secrets.ALTMETRIC_API_KEY }}'
      ALTMETRIC_API_SECRET: '${{ secrets.ALTMETRIC_API_SECRET }}'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi      
    - name: Set up Credentials files
      run: |
        echo -e '${{ secrets.GMAIL_CREDENTIALS }}' > credentials.json
        echo -e '${{ secrets.GMAIL_TOKEN }}' > token.json
    - name: run job
      run: |
        ./query.py
